added contact developer and demo for rating in settings
raxysstudios/andax pull request #1
Opened 2021-11-23 16:57 UTC by tasneem22

2021-11-24 08:10 UTC, aabounegm requested changes
Please make sure that the CI always passes. In this case, it was because of a syntax error from the merge conflict.
Also, I didn't check any changes under the `ios` folder as I don't understand what goes on there 😁

2021-11-24 08:10 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +                itemPadding: EdgeInsets.symmetric(horizontal: 4.0),
"Prefer const with constant constructors" - dart analyzer.
Please make sure that Android Studio shows you Dart Analyzer's messages

2021-11-24 08:10 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +              trailing: RatingBar.builder(
Do we really need this `RatingBar` package? It's not like the rating actually goes to the Play/App Store. I think it should just be a button that redirects to the relevant store.

2021-11-24 08:10 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +           )
There is an extra parenthesis left over from the merge conflict. This is what's preventing it from building

2021-12-08 18:59 UTC, aabounegm requested changes
When you request review, please make sure that all previous comments are addressed, that there are no merge conflicts, and that the CI passes.
In this case, the CI did not run because there are many merge conflicts. Please fix them first, and make sure you set up autoformatting with dartfmt.

2021-12-08 18:59 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +  // => _inAppReview.requestReview();
What is this comment?

2021-12-08 18:59 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +            )),
Don't forget trailing commas for better formatting

2021-12-08 18:59 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +    }
What are you using this `_availability` for?

2021-12-08 18:59 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +    void initState() {
What is this extra level of indentation? Are you sure you are using the dart formatter?

2021-12-08 18:59 UTC, aabounegm commented on lib/constants.dart
> +const kPlayStoreId = '';
I don't see these constants being used anywhere

2022-01-13 12:34 UTC, aabounegm approved these changes

2022-01-13 12:34 UTC, aabounegm commented on lib/screens/settings_screen.dart
> +  }
This override does nothing. You can remove it and `super.initState` will be implicitly called  anyways

2022-02-25 19:25 UTC, alkaitagi commented
@aabounegm must we close this?

2022-02-25 19:48 UTC, aabounegm commented
Yes I think we should. It would take more effort to bring it up to date than to reimplement the added feature

2022-02-25 21:01 UTC, closed without merging